version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
  selenium:
    image: b4handjr/selenium-firefox
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
  integration-tests:
    build: ./test/integration
    environment:
      - BASE_URL=${BASE_URL:-http://web:1443}
    links:
      - web
      - selenium
    volumes:
      - "./coverage:/coverage"
